<?php
/**
 * UsageBillingApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zarnite\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Zarnite\ApiException;
use Zarnite\Configuration;
use Zarnite\FormDataProcessor;
use Zarnite\HeaderSelector;
use Zarnite\ObjectSerializer;

/**
 * UsageBillingApi Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsageBillingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getOrgCreditsV1UsageCreditsGet' => [
            'application/json',
        ],
        'getOrgRagSessionLimitV1UsageRagSessionLimitGet' => [
            'application/json',
        ],
        'getOrgUsageV1UsageGet' => [
            'application/json',
        ],
        'getUsageLogsV1UsageLogsGet' => [
            'application/json',
        ],
        'updateOrgCreditsV1UsageCreditsPut' => [
            'application/json',
        ],
        'updateOrgRagSessionLimitV1UsageRagSessionLimitPut' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getOrgCreditsV1UsageCreditsGet
     *
     * Get Org Credits
     *
     * @param  string $org_id org_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgCreditsV1UsageCreditsGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zarnite\Model\EnvelopeOrgCreditWalletResponse|\Zarnite\Model\HTTPValidationError
     */
    public function getOrgCreditsV1UsageCreditsGet($org_id, string $contentType = self::contentTypes['getOrgCreditsV1UsageCreditsGet'][0])
    {
        list($response) = $this->getOrgCreditsV1UsageCreditsGetWithHttpInfo($org_id, $contentType);
        return $response;
    }

    /**
     * Operation getOrgCreditsV1UsageCreditsGetWithHttpInfo
     *
     * Get Org Credits
     *
     * @param  string $org_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgCreditsV1UsageCreditsGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zarnite\Model\EnvelopeOrgCreditWalletResponse|\Zarnite\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrgCreditsV1UsageCreditsGetWithHttpInfo($org_id, string $contentType = self::contentTypes['getOrgCreditsV1UsageCreditsGet'][0])
    {
        $request = $this->getOrgCreditsV1UsageCreditsGetRequest($org_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\EnvelopeOrgCreditWalletResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zarnite\Model\EnvelopeOrgCreditWalletResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\EnvelopeOrgCreditWalletResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOrgCreditsV1UsageCreditsGetAsync
     *
     * Get Org Credits
     *
     * @param  string $org_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgCreditsV1UsageCreditsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrgCreditsV1UsageCreditsGetAsync($org_id, string $contentType = self::contentTypes['getOrgCreditsV1UsageCreditsGet'][0])
    {
        return $this->getOrgCreditsV1UsageCreditsGetAsyncWithHttpInfo($org_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrgCreditsV1UsageCreditsGetAsyncWithHttpInfo
     *
     * Get Org Credits
     *
     * @param  string $org_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgCreditsV1UsageCreditsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrgCreditsV1UsageCreditsGetAsyncWithHttpInfo($org_id, string $contentType = self::contentTypes['getOrgCreditsV1UsageCreditsGet'][0])
    {
        $returnType = '\Zarnite\Model\EnvelopeOrgCreditWalletResponse';
        $request = $this->getOrgCreditsV1UsageCreditsGetRequest($org_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrgCreditsV1UsageCreditsGet'
     *
     * @param  string $org_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgCreditsV1UsageCreditsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOrgCreditsV1UsageCreditsGetRequest($org_id, string $contentType = self::contentTypes['getOrgCreditsV1UsageCreditsGet'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling getOrgCreditsV1UsageCreditsGet'
            );
        }


        $resourcePath = '/v1/usage/credits';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $org_id,
            'org_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getOrgRagSessionLimitV1UsageRagSessionLimitGet
     *
     * Get Org Rag Session Limit
     *
     * @param  string $org_id org_id (required)
     * @param  string|null $user_id user_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zarnite\Model\EnvelopeOrgRagSessionLimitResponse|\Zarnite\Model\HTTPValidationError
     */
    public function getOrgRagSessionLimitV1UsageRagSessionLimitGet($org_id, $user_id = null, string $contentType = self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'][0])
    {
        list($response) = $this->getOrgRagSessionLimitV1UsageRagSessionLimitGetWithHttpInfo($org_id, $user_id, $contentType);
        return $response;
    }

    /**
     * Operation getOrgRagSessionLimitV1UsageRagSessionLimitGetWithHttpInfo
     *
     * Get Org Rag Session Limit
     *
     * @param  string $org_id (required)
     * @param  string|null $user_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zarnite\Model\EnvelopeOrgRagSessionLimitResponse|\Zarnite\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrgRagSessionLimitV1UsageRagSessionLimitGetWithHttpInfo($org_id, $user_id = null, string $contentType = self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'][0])
    {
        $request = $this->getOrgRagSessionLimitV1UsageRagSessionLimitGetRequest($org_id, $user_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOrgRagSessionLimitV1UsageRagSessionLimitGetAsync
     *
     * Get Org Rag Session Limit
     *
     * @param  string $org_id (required)
     * @param  string|null $user_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrgRagSessionLimitV1UsageRagSessionLimitGetAsync($org_id, $user_id = null, string $contentType = self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'][0])
    {
        return $this->getOrgRagSessionLimitV1UsageRagSessionLimitGetAsyncWithHttpInfo($org_id, $user_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrgRagSessionLimitV1UsageRagSessionLimitGetAsyncWithHttpInfo
     *
     * Get Org Rag Session Limit
     *
     * @param  string $org_id (required)
     * @param  string|null $user_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrgRagSessionLimitV1UsageRagSessionLimitGetAsyncWithHttpInfo($org_id, $user_id = null, string $contentType = self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'][0])
    {
        $returnType = '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse';
        $request = $this->getOrgRagSessionLimitV1UsageRagSessionLimitGetRequest($org_id, $user_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrgRagSessionLimitV1UsageRagSessionLimitGet'
     *
     * @param  string $org_id (required)
     * @param  string|null $user_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOrgRagSessionLimitV1UsageRagSessionLimitGetRequest($org_id, $user_id = null, string $contentType = self::contentTypes['getOrgRagSessionLimitV1UsageRagSessionLimitGet'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling getOrgRagSessionLimitV1UsageRagSessionLimitGet'
            );
        }



        $resourcePath = '/v1/usage/rag-session-limit';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $org_id,
            'org_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $user_id,
            'user_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getOrgUsageV1UsageGet
     *
     * Get Org Usage
     *
     * @param  string $org_id org_id (required)
     * @param  \DateTime|null $start_date start_date (optional)
     * @param  \DateTime|null $end_date end_date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgUsageV1UsageGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zarnite\Model\EnvelopeAggregatedUsage|\Zarnite\Model\HTTPValidationError
     */
    public function getOrgUsageV1UsageGet($org_id, $start_date = null, $end_date = null, string $contentType = self::contentTypes['getOrgUsageV1UsageGet'][0])
    {
        list($response) = $this->getOrgUsageV1UsageGetWithHttpInfo($org_id, $start_date, $end_date, $contentType);
        return $response;
    }

    /**
     * Operation getOrgUsageV1UsageGetWithHttpInfo
     *
     * Get Org Usage
     *
     * @param  string $org_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgUsageV1UsageGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zarnite\Model\EnvelopeAggregatedUsage|\Zarnite\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrgUsageV1UsageGetWithHttpInfo($org_id, $start_date = null, $end_date = null, string $contentType = self::contentTypes['getOrgUsageV1UsageGet'][0])
    {
        $request = $this->getOrgUsageV1UsageGetRequest($org_id, $start_date, $end_date, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\EnvelopeAggregatedUsage',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zarnite\Model\EnvelopeAggregatedUsage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\EnvelopeAggregatedUsage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOrgUsageV1UsageGetAsync
     *
     * Get Org Usage
     *
     * @param  string $org_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgUsageV1UsageGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrgUsageV1UsageGetAsync($org_id, $start_date = null, $end_date = null, string $contentType = self::contentTypes['getOrgUsageV1UsageGet'][0])
    {
        return $this->getOrgUsageV1UsageGetAsyncWithHttpInfo($org_id, $start_date, $end_date, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrgUsageV1UsageGetAsyncWithHttpInfo
     *
     * Get Org Usage
     *
     * @param  string $org_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgUsageV1UsageGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrgUsageV1UsageGetAsyncWithHttpInfo($org_id, $start_date = null, $end_date = null, string $contentType = self::contentTypes['getOrgUsageV1UsageGet'][0])
    {
        $returnType = '\Zarnite\Model\EnvelopeAggregatedUsage';
        $request = $this->getOrgUsageV1UsageGetRequest($org_id, $start_date, $end_date, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrgUsageV1UsageGet'
     *
     * @param  string $org_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrgUsageV1UsageGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOrgUsageV1UsageGetRequest($org_id, $start_date = null, $end_date = null, string $contentType = self::contentTypes['getOrgUsageV1UsageGet'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling getOrgUsageV1UsageGet'
            );
        }




        $resourcePath = '/v1/usage/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $org_id,
            'org_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_date,
            'start_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_date,
            'end_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUsageLogsV1UsageLogsGet
     *
     * Get Usage Logs
     *
     * @param  string $org_id org_id (required)
     * @param  string|null $agent_id agent_id (optional)
     * @param  int|null $limit limit (optional, default to 100)
     * @param  int|null $offset offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUsageLogsV1UsageLogsGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zarnite\Model\EnvelopeListUsageLogEntry|\Zarnite\Model\HTTPValidationError
     */
    public function getUsageLogsV1UsageLogsGet($org_id, $agent_id = null, $limit = 100, $offset = 0, string $contentType = self::contentTypes['getUsageLogsV1UsageLogsGet'][0])
    {
        list($response) = $this->getUsageLogsV1UsageLogsGetWithHttpInfo($org_id, $agent_id, $limit, $offset, $contentType);
        return $response;
    }

    /**
     * Operation getUsageLogsV1UsageLogsGetWithHttpInfo
     *
     * Get Usage Logs
     *
     * @param  string $org_id (required)
     * @param  string|null $agent_id (optional)
     * @param  int|null $limit (optional, default to 100)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUsageLogsV1UsageLogsGet'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zarnite\Model\EnvelopeListUsageLogEntry|\Zarnite\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUsageLogsV1UsageLogsGetWithHttpInfo($org_id, $agent_id = null, $limit = 100, $offset = 0, string $contentType = self::contentTypes['getUsageLogsV1UsageLogsGet'][0])
    {
        $request = $this->getUsageLogsV1UsageLogsGetRequest($org_id, $agent_id, $limit, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\EnvelopeListUsageLogEntry',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zarnite\Model\EnvelopeListUsageLogEntry',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\EnvelopeListUsageLogEntry',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getUsageLogsV1UsageLogsGetAsync
     *
     * Get Usage Logs
     *
     * @param  string $org_id (required)
     * @param  string|null $agent_id (optional)
     * @param  int|null $limit (optional, default to 100)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUsageLogsV1UsageLogsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUsageLogsV1UsageLogsGetAsync($org_id, $agent_id = null, $limit = 100, $offset = 0, string $contentType = self::contentTypes['getUsageLogsV1UsageLogsGet'][0])
    {
        return $this->getUsageLogsV1UsageLogsGetAsyncWithHttpInfo($org_id, $agent_id, $limit, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUsageLogsV1UsageLogsGetAsyncWithHttpInfo
     *
     * Get Usage Logs
     *
     * @param  string $org_id (required)
     * @param  string|null $agent_id (optional)
     * @param  int|null $limit (optional, default to 100)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUsageLogsV1UsageLogsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUsageLogsV1UsageLogsGetAsyncWithHttpInfo($org_id, $agent_id = null, $limit = 100, $offset = 0, string $contentType = self::contentTypes['getUsageLogsV1UsageLogsGet'][0])
    {
        $returnType = '\Zarnite\Model\EnvelopeListUsageLogEntry';
        $request = $this->getUsageLogsV1UsageLogsGetRequest($org_id, $agent_id, $limit, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUsageLogsV1UsageLogsGet'
     *
     * @param  string $org_id (required)
     * @param  string|null $agent_id (optional)
     * @param  int|null $limit (optional, default to 100)
     * @param  int|null $offset (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUsageLogsV1UsageLogsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUsageLogsV1UsageLogsGetRequest($org_id, $agent_id = null, $limit = 100, $offset = 0, string $contentType = self::contentTypes['getUsageLogsV1UsageLogsGet'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling getUsageLogsV1UsageLogsGet'
            );
        }





        $resourcePath = '/v1/usage/logs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $org_id,
            'org_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $agent_id,
            'agent_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateOrgCreditsV1UsageCreditsPut
     *
     * Update Org Credits
     *
     * @param  string $org_id org_id (required)
     * @param  \Zarnite\Model\OrgCreditWalletUpdateRequest $org_credit_wallet_update_request org_credit_wallet_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgCreditsV1UsageCreditsPut'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zarnite\Model\EnvelopeOrgCreditWalletResponse|\Zarnite\Model\HTTPValidationError
     */
    public function updateOrgCreditsV1UsageCreditsPut($org_id, $org_credit_wallet_update_request, string $contentType = self::contentTypes['updateOrgCreditsV1UsageCreditsPut'][0])
    {
        list($response) = $this->updateOrgCreditsV1UsageCreditsPutWithHttpInfo($org_id, $org_credit_wallet_update_request, $contentType);
        return $response;
    }

    /**
     * Operation updateOrgCreditsV1UsageCreditsPutWithHttpInfo
     *
     * Update Org Credits
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgCreditWalletUpdateRequest $org_credit_wallet_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgCreditsV1UsageCreditsPut'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zarnite\Model\EnvelopeOrgCreditWalletResponse|\Zarnite\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateOrgCreditsV1UsageCreditsPutWithHttpInfo($org_id, $org_credit_wallet_update_request, string $contentType = self::contentTypes['updateOrgCreditsV1UsageCreditsPut'][0])
    {
        $request = $this->updateOrgCreditsV1UsageCreditsPutRequest($org_id, $org_credit_wallet_update_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\EnvelopeOrgCreditWalletResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zarnite\Model\EnvelopeOrgCreditWalletResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\EnvelopeOrgCreditWalletResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateOrgCreditsV1UsageCreditsPutAsync
     *
     * Update Org Credits
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgCreditWalletUpdateRequest $org_credit_wallet_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgCreditsV1UsageCreditsPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateOrgCreditsV1UsageCreditsPutAsync($org_id, $org_credit_wallet_update_request, string $contentType = self::contentTypes['updateOrgCreditsV1UsageCreditsPut'][0])
    {
        return $this->updateOrgCreditsV1UsageCreditsPutAsyncWithHttpInfo($org_id, $org_credit_wallet_update_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateOrgCreditsV1UsageCreditsPutAsyncWithHttpInfo
     *
     * Update Org Credits
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgCreditWalletUpdateRequest $org_credit_wallet_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgCreditsV1UsageCreditsPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateOrgCreditsV1UsageCreditsPutAsyncWithHttpInfo($org_id, $org_credit_wallet_update_request, string $contentType = self::contentTypes['updateOrgCreditsV1UsageCreditsPut'][0])
    {
        $returnType = '\Zarnite\Model\EnvelopeOrgCreditWalletResponse';
        $request = $this->updateOrgCreditsV1UsageCreditsPutRequest($org_id, $org_credit_wallet_update_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateOrgCreditsV1UsageCreditsPut'
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgCreditWalletUpdateRequest $org_credit_wallet_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgCreditsV1UsageCreditsPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateOrgCreditsV1UsageCreditsPutRequest($org_id, $org_credit_wallet_update_request, string $contentType = self::contentTypes['updateOrgCreditsV1UsageCreditsPut'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling updateOrgCreditsV1UsageCreditsPut'
            );
        }

        // verify the required parameter 'org_credit_wallet_update_request' is set
        if ($org_credit_wallet_update_request === null || (is_array($org_credit_wallet_update_request) && count($org_credit_wallet_update_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_credit_wallet_update_request when calling updateOrgCreditsV1UsageCreditsPut'
            );
        }


        $resourcePath = '/v1/usage/credits';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $org_id,
            'org_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($org_credit_wallet_update_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($org_credit_wallet_update_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $org_credit_wallet_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateOrgRagSessionLimitV1UsageRagSessionLimitPut
     *
     * Update Org Rag Session Limit
     *
     * @param  string $org_id org_id (required)
     * @param  \Zarnite\Model\OrgRagSessionLimitUpdateRequest $org_rag_session_limit_update_request org_rag_session_limit_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zarnite\Model\EnvelopeOrgRagSessionLimitResponse|\Zarnite\Model\HTTPValidationError
     */
    public function updateOrgRagSessionLimitV1UsageRagSessionLimitPut($org_id, $org_rag_session_limit_update_request, string $contentType = self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'][0])
    {
        list($response) = $this->updateOrgRagSessionLimitV1UsageRagSessionLimitPutWithHttpInfo($org_id, $org_rag_session_limit_update_request, $contentType);
        return $response;
    }

    /**
     * Operation updateOrgRagSessionLimitV1UsageRagSessionLimitPutWithHttpInfo
     *
     * Update Org Rag Session Limit
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgRagSessionLimitUpdateRequest $org_rag_session_limit_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'] to see the possible values for this operation
     *
     * @throws \Zarnite\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zarnite\Model\EnvelopeOrgRagSessionLimitResponse|\Zarnite\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateOrgRagSessionLimitV1UsageRagSessionLimitPutWithHttpInfo($org_id, $org_rag_session_limit_update_request, string $contentType = self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'][0])
    {
        $request = $this->updateOrgRagSessionLimitV1UsageRagSessionLimitPutRequest($org_id, $org_rag_session_limit_update_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Zarnite\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zarnite\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateOrgRagSessionLimitV1UsageRagSessionLimitPutAsync
     *
     * Update Org Rag Session Limit
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgRagSessionLimitUpdateRequest $org_rag_session_limit_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateOrgRagSessionLimitV1UsageRagSessionLimitPutAsync($org_id, $org_rag_session_limit_update_request, string $contentType = self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'][0])
    {
        return $this->updateOrgRagSessionLimitV1UsageRagSessionLimitPutAsyncWithHttpInfo($org_id, $org_rag_session_limit_update_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateOrgRagSessionLimitV1UsageRagSessionLimitPutAsyncWithHttpInfo
     *
     * Update Org Rag Session Limit
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgRagSessionLimitUpdateRequest $org_rag_session_limit_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateOrgRagSessionLimitV1UsageRagSessionLimitPutAsyncWithHttpInfo($org_id, $org_rag_session_limit_update_request, string $contentType = self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'][0])
    {
        $returnType = '\Zarnite\Model\EnvelopeOrgRagSessionLimitResponse';
        $request = $this->updateOrgRagSessionLimitV1UsageRagSessionLimitPutRequest($org_id, $org_rag_session_limit_update_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateOrgRagSessionLimitV1UsageRagSessionLimitPut'
     *
     * @param  string $org_id (required)
     * @param  \Zarnite\Model\OrgRagSessionLimitUpdateRequest $org_rag_session_limit_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateOrgRagSessionLimitV1UsageRagSessionLimitPutRequest($org_id, $org_rag_session_limit_update_request, string $contentType = self::contentTypes['updateOrgRagSessionLimitV1UsageRagSessionLimitPut'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling updateOrgRagSessionLimitV1UsageRagSessionLimitPut'
            );
        }

        // verify the required parameter 'org_rag_session_limit_update_request' is set
        if ($org_rag_session_limit_update_request === null || (is_array($org_rag_session_limit_update_request) && count($org_rag_session_limit_update_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_rag_session_limit_update_request when calling updateOrgRagSessionLimitV1UsageRagSessionLimitPut'
            );
        }


        $resourcePath = '/v1/usage/rag-session-limit';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $org_id,
            'org_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($org_rag_session_limit_update_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($org_rag_session_limit_update_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $org_rag_session_limit_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
