<?php
/**
 * LearnerScoreResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zarnite\Model;

use \ArrayAccess;
use \Zarnite\ObjectSerializer;

/**
 * LearnerScoreResponse Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LearnerScoreResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LearnerScoreResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'learner_id' => 'string',
        'score' => 'int',
        'cefr_level' => 'string',
        'breakdown' => '\Zarnite\Model\ScoreBreakdown',
        'recommendation' => 'string',
        'assessed_at' => 'string',
        'rubric_type' => 'string',
        'rubric_reasoning' => 'string',
        'evaluation_mode' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'learner_id' => null,
        'score' => null,
        'cefr_level' => null,
        'breakdown' => null,
        'recommendation' => null,
        'assessed_at' => null,
        'rubric_type' => null,
        'rubric_reasoning' => null,
        'evaluation_mode' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'learner_id' => false,
        'score' => false,
        'cefr_level' => false,
        'breakdown' => false,
        'recommendation' => false,
        'assessed_at' => false,
        'rubric_type' => true,
        'rubric_reasoning' => true,
        'evaluation_mode' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'learner_id' => 'learnerId',
        'score' => 'score',
        'cefr_level' => 'cefrLevel',
        'breakdown' => 'breakdown',
        'recommendation' => 'recommendation',
        'assessed_at' => 'assessedAt',
        'rubric_type' => 'rubricType',
        'rubric_reasoning' => 'rubricReasoning',
        'evaluation_mode' => 'evaluationMode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'learner_id' => 'setLearnerId',
        'score' => 'setScore',
        'cefr_level' => 'setCefrLevel',
        'breakdown' => 'setBreakdown',
        'recommendation' => 'setRecommendation',
        'assessed_at' => 'setAssessedAt',
        'rubric_type' => 'setRubricType',
        'rubric_reasoning' => 'setRubricReasoning',
        'evaluation_mode' => 'setEvaluationMode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'learner_id' => 'getLearnerId',
        'score' => 'getScore',
        'cefr_level' => 'getCefrLevel',
        'breakdown' => 'getBreakdown',
        'recommendation' => 'getRecommendation',
        'assessed_at' => 'getAssessedAt',
        'rubric_type' => 'getRubricType',
        'rubric_reasoning' => 'getRubricReasoning',
        'evaluation_mode' => 'getEvaluationMode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('learner_id', $data ?? [], null);
        $this->setIfExists('score', $data ?? [], null);
        $this->setIfExists('cefr_level', $data ?? [], null);
        $this->setIfExists('breakdown', $data ?? [], null);
        $this->setIfExists('recommendation', $data ?? [], null);
        $this->setIfExists('assessed_at', $data ?? [], null);
        $this->setIfExists('rubric_type', $data ?? [], null);
        $this->setIfExists('rubric_reasoning', $data ?? [], null);
        $this->setIfExists('evaluation_mode', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['learner_id'] === null) {
            $invalidProperties[] = "'learner_id' can't be null";
        }
        if ($this->container['score'] === null) {
            $invalidProperties[] = "'score' can't be null";
        }
        if ($this->container['cefr_level'] === null) {
            $invalidProperties[] = "'cefr_level' can't be null";
        }
        if ($this->container['breakdown'] === null) {
            $invalidProperties[] = "'breakdown' can't be null";
        }
        if ($this->container['recommendation'] === null) {
            $invalidProperties[] = "'recommendation' can't be null";
        }
        if ($this->container['assessed_at'] === null) {
            $invalidProperties[] = "'assessed_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets learner_id
     *
     * @return string
     */
    public function getLearnerId()
    {
        return $this->container['learner_id'];
    }

    /**
     * Sets learner_id
     *
     * @param string $learner_id Learner identifier
     *
     * @return self
     */
    public function setLearnerId($learner_id)
    {
        if (is_null($learner_id)) {
            throw new \InvalidArgumentException('non-nullable learner_id cannot be null');
        }
        $this->container['learner_id'] = $learner_id;

        return $this;
    }

    /**
     * Gets score
     *
     * @return int
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param int $score Overall proficiency score (0-100)
     *
     * @return self
     */
    public function setScore($score)
    {
        if (is_null($score)) {
            throw new \InvalidArgumentException('non-nullable score cannot be null');
        }
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets cefr_level
     *
     * @return string
     */
    public function getCefrLevel()
    {
        return $this->container['cefr_level'];
    }

    /**
     * Sets cefr_level
     *
     * @param string $cefr_level CEFR level (A1-C2)
     *
     * @return self
     */
    public function setCefrLevel($cefr_level)
    {
        if (is_null($cefr_level)) {
            throw new \InvalidArgumentException('non-nullable cefr_level cannot be null');
        }
        $this->container['cefr_level'] = $cefr_level;

        return $this;
    }

    /**
     * Gets breakdown
     *
     * @return \Zarnite\Model\ScoreBreakdown
     */
    public function getBreakdown()
    {
        return $this->container['breakdown'];
    }

    /**
     * Sets breakdown
     *
     * @param \Zarnite\Model\ScoreBreakdown $breakdown Per-dimension score breakdown
     *
     * @return self
     */
    public function setBreakdown($breakdown)
    {
        if (is_null($breakdown)) {
            throw new \InvalidArgumentException('non-nullable breakdown cannot be null');
        }
        $this->container['breakdown'] = $breakdown;

        return $this;
    }

    /**
     * Gets recommendation
     *
     * @return string
     */
    public function getRecommendation()
    {
        return $this->container['recommendation'];
    }

    /**
     * Sets recommendation
     *
     * @param string $recommendation AI-generated recommendation text
     *
     * @return self
     */
    public function setRecommendation($recommendation)
    {
        if (is_null($recommendation)) {
            throw new \InvalidArgumentException('non-nullable recommendation cannot be null');
        }
        $this->container['recommendation'] = $recommendation;

        return $this;
    }

    /**
     * Gets assessed_at
     *
     * @return string
     */
    public function getAssessedAt()
    {
        return $this->container['assessed_at'];
    }

    /**
     * Sets assessed_at
     *
     * @param string $assessed_at ISO timestamp of assessment
     *
     * @return self
     */
    public function setAssessedAt($assessed_at)
    {
        if (is_null($assessed_at)) {
            throw new \InvalidArgumentException('non-nullable assessed_at cannot be null');
        }
        $this->container['assessed_at'] = $assessed_at;

        return $this;
    }

    /**
     * Gets rubric_type
     *
     * @return string|null
     */
    public function getRubricType()
    {
        return $this->container['rubric_type'];
    }

    /**
     * Sets rubric_type
     *
     * @param string|null $rubric_type Evaluation rubric used for scoring
     *
     * @return self
     */
    public function setRubricType($rubric_type)
    {
        if (is_null($rubric_type)) {
            array_push($this->openAPINullablesSetToNull, 'rubric_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rubric_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rubric_type'] = $rubric_type;

        return $this;
    }

    /**
     * Gets rubric_reasoning
     *
     * @return string|null
     */
    public function getRubricReasoning()
    {
        return $this->container['rubric_reasoning'];
    }

    /**
     * Sets rubric_reasoning
     *
     * @param string|null $rubric_reasoning Short explanation of why the rubric was selected
     *
     * @return self
     */
    public function setRubricReasoning($rubric_reasoning)
    {
        if (is_null($rubric_reasoning)) {
            array_push($this->openAPINullablesSetToNull, 'rubric_reasoning');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rubric_reasoning', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rubric_reasoning'] = $rubric_reasoning;

        return $this;
    }

    /**
     * Gets evaluation_mode
     *
     * @return string|null
     */
    public function getEvaluationMode()
    {
        return $this->container['evaluation_mode'];
    }

    /**
     * Sets evaluation_mode
     *
     * @param string|null $evaluation_mode Scoring mode, e.g. heuristic or llm_hybrid
     *
     * @return self
     */
    public function setEvaluationMode($evaluation_mode)
    {
        if (is_null($evaluation_mode)) {
            array_push($this->openAPINullablesSetToNull, 'evaluation_mode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('evaluation_mode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['evaluation_mode'] = $evaluation_mode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


