<?php
/**
 * LearnerDeletionScheduleResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zarnite\Model;

use \ArrayAccess;
use \Zarnite\ObjectSerializer;

/**
 * LearnerDeletionScheduleResponse Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LearnerDeletionScheduleResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LearnerDeletionScheduleResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'learner_id' => 'string',
        'scheduled' => 'bool',
        'requested_at' => '\DateTime',
        'scheduled_for' => '\DateTime',
        'requested_by' => 'string',
        'days_remaining' => 'int',
        'cancellable' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'learner_id' => null,
        'scheduled' => null,
        'requested_at' => 'date-time',
        'scheduled_for' => 'date-time',
        'requested_by' => null,
        'days_remaining' => null,
        'cancellable' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'learner_id' => false,
        'scheduled' => false,
        'requested_at' => true,
        'scheduled_for' => true,
        'requested_by' => true,
        'days_remaining' => true,
        'cancellable' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'learner_id' => 'learnerId',
        'scheduled' => 'scheduled',
        'requested_at' => 'requestedAt',
        'scheduled_for' => 'scheduledFor',
        'requested_by' => 'requestedBy',
        'days_remaining' => 'daysRemaining',
        'cancellable' => 'cancellable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'learner_id' => 'setLearnerId',
        'scheduled' => 'setScheduled',
        'requested_at' => 'setRequestedAt',
        'scheduled_for' => 'setScheduledFor',
        'requested_by' => 'setRequestedBy',
        'days_remaining' => 'setDaysRemaining',
        'cancellable' => 'setCancellable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'learner_id' => 'getLearnerId',
        'scheduled' => 'getScheduled',
        'requested_at' => 'getRequestedAt',
        'scheduled_for' => 'getScheduledFor',
        'requested_by' => 'getRequestedBy',
        'days_remaining' => 'getDaysRemaining',
        'cancellable' => 'getCancellable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('learner_id', $data ?? [], null);
        $this->setIfExists('scheduled', $data ?? [], null);
        $this->setIfExists('requested_at', $data ?? [], null);
        $this->setIfExists('scheduled_for', $data ?? [], null);
        $this->setIfExists('requested_by', $data ?? [], null);
        $this->setIfExists('days_remaining', $data ?? [], null);
        $this->setIfExists('cancellable', $data ?? [], false);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['learner_id'] === null) {
            $invalidProperties[] = "'learner_id' can't be null";
        }
        if ($this->container['scheduled'] === null) {
            $invalidProperties[] = "'scheduled' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets learner_id
     *
     * @return string
     */
    public function getLearnerId()
    {
        return $this->container['learner_id'];
    }

    /**
     * Sets learner_id
     *
     * @param string $learner_id Learner identifier
     *
     * @return self
     */
    public function setLearnerId($learner_id)
    {
        if (is_null($learner_id)) {
            throw new \InvalidArgumentException('non-nullable learner_id cannot be null');
        }
        $this->container['learner_id'] = $learner_id;

        return $this;
    }

    /**
     * Gets scheduled
     *
     * @return bool
     */
    public function getScheduled()
    {
        return $this->container['scheduled'];
    }

    /**
     * Sets scheduled
     *
     * @param bool $scheduled Whether learner deletion is currently scheduled
     *
     * @return self
     */
    public function setScheduled($scheduled)
    {
        if (is_null($scheduled)) {
            throw new \InvalidArgumentException('non-nullable scheduled cannot be null');
        }
        $this->container['scheduled'] = $scheduled;

        return $this;
    }

    /**
     * Gets requested_at
     *
     * @return \DateTime|null
     */
    public function getRequestedAt()
    {
        return $this->container['requested_at'];
    }

    /**
     * Sets requested_at
     *
     * @param \DateTime|null $requested_at When deletion was requested
     *
     * @return self
     */
    public function setRequestedAt($requested_at)
    {
        if (is_null($requested_at)) {
            array_push($this->openAPINullablesSetToNull, 'requested_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requested_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requested_at'] = $requested_at;

        return $this;
    }

    /**
     * Gets scheduled_for
     *
     * @return \DateTime|null
     */
    public function getScheduledFor()
    {
        return $this->container['scheduled_for'];
    }

    /**
     * Sets scheduled_for
     *
     * @param \DateTime|null $scheduled_for When learner deletion will execute
     *
     * @return self
     */
    public function setScheduledFor($scheduled_for)
    {
        if (is_null($scheduled_for)) {
            array_push($this->openAPINullablesSetToNull, 'scheduled_for');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scheduled_for', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['scheduled_for'] = $scheduled_for;

        return $this;
    }

    /**
     * Gets requested_by
     *
     * @return string|null
     */
    public function getRequestedBy()
    {
        return $this->container['requested_by'];
    }

    /**
     * Sets requested_by
     *
     * @param string|null $requested_by Identifier for the admin who scheduled deletion
     *
     * @return self
     */
    public function setRequestedBy($requested_by)
    {
        if (is_null($requested_by)) {
            array_push($this->openAPINullablesSetToNull, 'requested_by');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requested_by', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requested_by'] = $requested_by;

        return $this;
    }

    /**
     * Gets days_remaining
     *
     * @return int|null
     */
    public function getDaysRemaining()
    {
        return $this->container['days_remaining'];
    }

    /**
     * Sets days_remaining
     *
     * @param int|null $days_remaining Whole days remaining until deletion executes
     *
     * @return self
     */
    public function setDaysRemaining($days_remaining)
    {
        if (is_null($days_remaining)) {
            array_push($this->openAPINullablesSetToNull, 'days_remaining');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('days_remaining', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['days_remaining'] = $days_remaining;

        return $this;
    }

    /**
     * Gets cancellable
     *
     * @return bool|null
     */
    public function getCancellable()
    {
        return $this->container['cancellable'];
    }

    /**
     * Sets cancellable
     *
     * @param bool|null $cancellable Whether deletion can still be cancelled
     *
     * @return self
     */
    public function setCancellable($cancellable)
    {
        if (is_null($cancellable)) {
            throw new \InvalidArgumentException('non-nullable cancellable cannot be null');
        }
        $this->container['cancellable'] = $cancellable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


