<?php
/**
 * OrganizationAnalyticsResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zarnite\Model;

use \ArrayAccess;
use \Zarnite\ObjectSerializer;

/**
 * OrganizationAnalyticsResponse Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrganizationAnalyticsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'OrganizationAnalyticsResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'range' => 'string',
        'view' => 'string',
        'classes' => 'string[]',
        'date_ranges' => 'string[]',
        'institution' => 'array<string,mixed>',
        'agents' => 'array<string,mixed>[]',
        'students' => 'array<string,mixed>[]',
        'student_detail' => 'array<string,mixed>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'range' => null,
        'view' => null,
        'classes' => null,
        'date_ranges' => null,
        'institution' => null,
        'agents' => null,
        'students' => null,
        'student_detail' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'range' => false,
        'view' => false,
        'classes' => false,
        'date_ranges' => false,
        'institution' => false,
        'agents' => false,
        'students' => false,
        'student_detail' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'range' => 'range',
        'view' => 'view',
        'classes' => 'classes',
        'date_ranges' => 'dateRanges',
        'institution' => 'institution',
        'agents' => 'agents',
        'students' => 'students',
        'student_detail' => 'studentDetail'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'range' => 'setRange',
        'view' => 'setView',
        'classes' => 'setClasses',
        'date_ranges' => 'setDateRanges',
        'institution' => 'setInstitution',
        'agents' => 'setAgents',
        'students' => 'setStudents',
        'student_detail' => 'setStudentDetail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'range' => 'getRange',
        'view' => 'getView',
        'classes' => 'getClasses',
        'date_ranges' => 'getDateRanges',
        'institution' => 'getInstitution',
        'agents' => 'getAgents',
        'students' => 'getStudents',
        'student_detail' => 'getStudentDetail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('range', $data ?? [], null);
        $this->setIfExists('view', $data ?? [], null);
        $this->setIfExists('classes', $data ?? [], null);
        $this->setIfExists('date_ranges', $data ?? [], null);
        $this->setIfExists('institution', $data ?? [], null);
        $this->setIfExists('agents', $data ?? [], null);
        $this->setIfExists('students', $data ?? [], null);
        $this->setIfExists('student_detail', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['range'] === null) {
            $invalidProperties[] = "'range' can't be null";
        }
        if ($this->container['view'] === null) {
            $invalidProperties[] = "'view' can't be null";
        }
        if ($this->container['institution'] === null) {
            $invalidProperties[] = "'institution' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets range
     *
     * @return string
     */
    public function getRange()
    {
        return $this->container['range'];
    }

    /**
     * Sets range
     *
     * @param string $range Selected range label
     *
     * @return self
     */
    public function setRange($range)
    {
        if (is_null($range)) {
            throw new \InvalidArgumentException('non-nullable range cannot be null');
        }
        $this->container['range'] = $range;

        return $this;
    }

    /**
     * Gets view
     *
     * @return string
     */
    public function getView()
    {
        return $this->container['view'];
    }

    /**
     * Sets view
     *
     * @param string $view Selected analytics lens
     *
     * @return self
     */
    public function setView($view)
    {
        if (is_null($view)) {
            throw new \InvalidArgumentException('non-nullable view cannot be null');
        }
        $this->container['view'] = $view;

        return $this;
    }

    /**
     * Gets classes
     *
     * @return string[]|null
     */
    public function getClasses()
    {
        return $this->container['classes'];
    }

    /**
     * Sets classes
     *
     * @param string[]|null $classes Available class filters
     *
     * @return self
     */
    public function setClasses($classes)
    {
        if (is_null($classes)) {
            throw new \InvalidArgumentException('non-nullable classes cannot be null');
        }
        $this->container['classes'] = $classes;

        return $this;
    }

    /**
     * Gets date_ranges
     *
     * @return string[]|null
     */
    public function getDateRanges()
    {
        return $this->container['date_ranges'];
    }

    /**
     * Sets date_ranges
     *
     * @param string[]|null $date_ranges Available date ranges
     *
     * @return self
     */
    public function setDateRanges($date_ranges)
    {
        if (is_null($date_ranges)) {
            throw new \InvalidArgumentException('non-nullable date_ranges cannot be null');
        }
        $this->container['date_ranges'] = $date_ranges;

        return $this;
    }

    /**
     * Gets institution
     *
     * @return array<string,mixed>
     */
    public function getInstitution()
    {
        return $this->container['institution'];
    }

    /**
     * Sets institution
     *
     * @param array<string,mixed> $institution Institution overview payload
     *
     * @return self
     */
    public function setInstitution($institution)
    {
        if (is_null($institution)) {
            throw new \InvalidArgumentException('non-nullable institution cannot be null');
        }
        $this->container['institution'] = $institution;

        return $this;
    }

    /**
     * Gets agents
     *
     * @return array<string,mixed>[]|null
     */
    public function getAgents()
    {
        return $this->container['agents'];
    }

    /**
     * Sets agents
     *
     * @param array<string,mixed>[]|null $agents Agent performance payload
     *
     * @return self
     */
    public function setAgents($agents)
    {
        if (is_null($agents)) {
            throw new \InvalidArgumentException('non-nullable agents cannot be null');
        }
        $this->container['agents'] = $agents;

        return $this;
    }

    /**
     * Gets students
     *
     * @return array<string,mixed>[]|null
     */
    public function getStudents()
    {
        return $this->container['students'];
    }

    /**
     * Sets students
     *
     * @param array<string,mixed>[]|null $students Student list payload
     *
     * @return self
     */
    public function setStudents($students)
    {
        if (is_null($students)) {
            throw new \InvalidArgumentException('non-nullable students cannot be null');
        }
        $this->container['students'] = $students;

        return $this;
    }

    /**
     * Gets student_detail
     *
     * @return array<string,mixed>|null
     */
    public function getStudentDetail()
    {
        return $this->container['student_detail'];
    }

    /**
     * Sets student_detail
     *
     * @param array<string,mixed>|null $student_detail Selected student detail payload
     *
     * @return self
     */
    public function setStudentDetail($student_detail)
    {
        if (is_null($student_detail)) {
            array_push($this->openAPINullablesSetToNull, 'student_detail');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('student_detail', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['student_detail'] = $student_detail;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


