<?php
/**
 * BodyUploadPreviewDocumentsV1PlaygroundPreviewDocumentsPostTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zarnite\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BodyUploadPreviewDocumentsV1PlaygroundPreviewDocumentsPostTest Class Doc Comment
 *
 * @category    Class
 * @description BodyUploadPreviewDocumentsV1PlaygroundPreviewDocumentsPost
 * @package     Zarnite
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BodyUploadPreviewDocumentsV1PlaygroundPreviewDocumentsPostTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BodyUploadPreviewDocumentsV1PlaygroundPreviewDocumentsPost"
     */
    public function testBodyUploadPreviewDocumentsV1PlaygroundPreviewDocumentsPost()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "org_id"
     */
    public function testPropertyOrgId()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "preview_agent_id"
     */
    public function testPropertyPreviewAgentId()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
        // TODO: implement
        self::assertTrue(true);
    }
}
