<?php
/**
 * PlaygroundPublicSessionRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zarnite\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PlaygroundPublicSessionRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PlaygroundPublicSessionRequest
 * @package     Zarnite
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PlaygroundPublicSessionRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PlaygroundPublicSessionRequest"
     */
    public function testPlaygroundPublicSessionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "org_id"
     */
    public function testPropertyOrgId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_prompt"
     */
    public function testPropertySystemPrompt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tone"
     */
    public function testPropertyTone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "strictness"
     */
    public function testPropertyStrictness()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voice"
     */
    public function testPropertyVoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "guardrails"
     */
    public function testPropertyGuardrails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "behavior"
     */
    public function testPropertyBehavior()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preview_agent_id"
     */
    public function testPropertyPreviewAgentId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "enable_knowledge_base"
     */
    public function testPropertyEnableKnowledgeBase()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "knowledge_base_agent_ids"
     */
    public function testPropertyKnowledgeBaseAgentIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "learner_id"
     */
    public function testPropertyLearnerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "thread_id"
     */
    public function testPropertyThreadId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_duration_s"
     */
    public function testPropertyMaxDurationS()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
