<?php
/**
 * UserSummaryResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zarnite\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UserSummaryResponseTest Class Doc Comment
 *
 * @category    Class
 * @description UserSummaryResponse
 * @package     Zarnite
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserSummaryResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserSummaryResponse"
     */
    public function testUserSummaryResponse()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "org_id"
     */
    public function testPropertyOrgId()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "agent_id"
     */
    public function testPropertyAgentId()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "first_activity"
     */
    public function testPropertyFirstActivity()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "last_activity"
     */
    public function testPropertyLastActivity()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "sessions"
     */
    public function testPropertySessions()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test attribute "most_active_hours"
     */
    public function testPropertyMostActiveHours()
    {
        // TODO: implement
        self::assertTrue(true);
    }
}
