<?php
/**
 * AgentsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Zarnite\Test\Api;

use \Zarnite\Configuration;
use \Zarnite\ApiException;
use \Zarnite\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AgentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AgentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for assignLearnerV1AgentsAgentIdAssignmentsPost
     *
     * Assign Learner.
     *
     */
    public function testAssignLearnerV1AgentsAgentIdAssignmentsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAgentV1AgentsPost
     *
     * Create Agent.
     *
     */
    public function testCreateAgentV1AgentsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAgentV1AgentsAgentIdDelete
     *
     * Delete Agent.
     *
     */
    public function testDeleteAgentV1AgentsAgentIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAgentV1AgentsAgentIdGet
     *
     * Get Agent.
     *
     */
    public function testGetAgentV1AgentsAgentIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAgentsV1AgentsGet
     *
     * List Agents.
     *
     */
    public function testListAgentsV1AgentsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssignmentsV1AgentsAgentIdAssignmentsGet
     *
     * List Assignments.
     *
     */
    public function testListAssignmentsV1AgentsAgentIdAssignmentsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeAssignmentV1AgentsAgentIdAssignmentsLearnerIdDelete
     *
     * Revoke Assignment.
     *
     */
    public function testRevokeAssignmentV1AgentsAgentIdAssignmentsLearnerIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAgentV1AgentsAgentIdPatch
     *
     * Update Agent.
     *
     */
    public function testUpdateAgentV1AgentsAgentIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAgentV1AgentsAgentIdPut
     *
     * Update Agent.
     *
     */
    public function testUpdateAgentV1AgentsAgentIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
