<?php
/**
 * APIKeysApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Zarnite\Test\Api;

use \Zarnite\Configuration;
use \Zarnite\ApiException;
use \Zarnite\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * APIKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class APIKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiKeyStatsV1ApiKeysStatsGet
     *
     * Api Key Stats.
     *
     */
    public function testApiKeyStatsV1ApiKeysStatsGet()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test case for createApiKeyV1ApiKeysPost
     *
     * Create Api Key.
     *
     */
    public function testCreateApiKeyV1ApiKeysPost()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test case for listApiKeysV1ApiKeysGet
     *
     * List Api Keys.
     *
     */
    public function testListApiKeysV1ApiKeysGet()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test case for revokeApiKeyV1ApiKeysKeyIdDelete
     *
     * Revoke Api Key.
     *
     */
    public function testRevokeApiKeyV1ApiKeysKeyIdDelete()
    {
        // TODO: implement
        self::assertTrue(true);
    }

    /**
     * Test case for updateApiKeyV1ApiKeysKeyIdPut
     *
     * Update Api Key.
     *
     */
    public function testUpdateApiKeyV1ApiKeysKeyIdPut()
    {
        // TODO: implement
        self::assertTrue(true);
    }
}
