<?php
/**
 * KnowledgeApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Zarnite\Test\Api;

use Zarnite\Api\KnowledgeApi;
use Zarnite\Configuration;
use PHPUnit\Framework\TestCase;

/**
 * KnowledgeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KnowledgeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteAgentDocumentV1AgentsAgentIdDocumentsDocumentIdDelete
     *
     * Delete Agent Document.
     *
     */
    public function testDeleteAgentDocumentV1AgentsAgentIdDocumentsDocumentIdDelete()
    {
        $config = new Configuration();
        $config->setHost('https://api.zarnite.com');
        $config->setAccessToken('test_token');

        $api = new KnowledgeApi(null, $config);
        $request = $api->deleteAgentDocumentV1AgentsAgentIdDocumentsDocumentIdDeleteRequest('agent_1', 'doc_1', 'org_1');
        $uri = (string) $request->getUri();

        self::assertSame('DELETE', $request->getMethod());
        self::assertStringContainsString('/v1/agents/agent_1/documents/doc_1', $uri);
        self::assertStringContainsString('org_id=org_1', $uri);
        self::assertSame('Bearer test_token', $request->getHeaderLine('Authorization'));
    }

    /**
     * Test case for deleteOrgDocumentV1KnowledgeDocumentsDocumentIdDelete
     *
     * Delete Org Document.
     *
     */
    public function testDeleteOrgDocumentV1KnowledgeDocumentsDocumentIdDelete()
    {
        $config = new Configuration();
        $config->setHost('https://api.zarnite.com');
        $config->setAccessToken('test_token');

        $api = new KnowledgeApi(null, $config);
        $request = $api->deleteOrgDocumentV1KnowledgeDocumentsDocumentIdDeleteRequest('doc_1', 'org_1');
        $uri = (string) $request->getUri();

        self::assertSame('DELETE', $request->getMethod());
        self::assertStringContainsString('/v1/knowledge/documents/doc_1', $uri);
        self::assertStringContainsString('org_id=org_1', $uri);
        self::assertSame('Bearer test_token', $request->getHeaderLine('Authorization'));
    }

    /**
     * Test case for listAgentDocumentsV1AgentsAgentIdDocumentsGet
     *
     * List Agent Documents.
     *
     */
    public function testListAgentDocumentsV1AgentsAgentIdDocumentsGet()
    {
        $api = new KnowledgeApi();
        $request = $api->listAgentDocumentsV1AgentsAgentIdDocumentsGetRequest('agent_1', 'org_1');
        $uri = (string) $request->getUri();

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/agents/agent_1/documents', $uri);
        self::assertStringContainsString('org_id=org_1', $uri);
    }

    /**
     * Test case for listOrgDocumentsV1KnowledgeDocumentsGet
     *
     * List Org Documents.
     *
     */
    public function testListOrgDocumentsV1KnowledgeDocumentsGet()
    {
        $config = new Configuration();
        $config->setHost('https://api.zarnite.com');

        $api = new KnowledgeApi(null, $config);
        $request = $api->listOrgDocumentsV1KnowledgeDocumentsGetRequest('org_1');
        $uri = (string) $request->getUri();

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/knowledge/documents', $uri);
        self::assertStringContainsString('org_id=org_1', $uri);
    }

    /**
     * Test case for uploadAgentDocumentV1AgentsAgentIdDocumentsPost
     *
     * Upload Agent Document.
     *
     */
    public function testUploadAgentDocumentV1AgentsAgentIdDocumentsPost()
    {
        $config = new Configuration();
        $config->setHost('https://api.zarnite.com');

        $api = new KnowledgeApi(null, $config);
        $request = $api->uploadAgentDocumentV1AgentsAgentIdDocumentsPostRequest('agent_1', 'dummy.txt', 'org_1', 'user_1');
        $body = (string) $request->getBody();

        self::assertSame('POST', $request->getMethod());
        self::assertStringContainsString('/v1/agents/agent_1/documents', (string) $request->getUri());
        self::assertStringContainsString('name="org_id"', $body);
        self::assertStringContainsString('org_1', $body);
        self::assertStringContainsString('name="user_id"', $body);
        self::assertStringContainsString('user_1', $body);
    }

    /**
     * Test case for uploadOrgDocumentV1KnowledgeDocumentsPost
     *
     * Upload Org Document.
     *
     */
    public function testUploadOrgDocumentV1KnowledgeDocumentsPost()
    {
        $api = new KnowledgeApi();

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $file when calling uploadOrgDocumentV1KnowledgeDocumentsPost');

        $api->uploadOrgDocumentV1KnowledgeDocumentsPostRequest(null, 'org_1');
    }
}
