<?php
/**
 * PlaygroundApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Zarnite\Test\Api;

use Zarnite\Api\PlaygroundApi;
use \Zarnite\Configuration;
use \Zarnite\ApiException;
use \Zarnite\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PlaygroundApiTest Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PlaygroundApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bootstrapSessionV1PlaygroundSessionsPost
     *
     * Bootstrap Session.
     *
     */
    public function testBootstrapSessionV1PlaygroundSessionsPost()
    {
        $api = new PlaygroundApi();

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $playground_session_request when calling bootstrapSessionV1PlaygroundSessionsPost');

        $api->bootstrapSessionV1PlaygroundSessionsPostRequest(null);
    }

    /**
     * Test case for endSessionV1PlaygroundSessionsSessionIdEndPost
     *
     * End Session.
     *
     */
    public function testEndSessionV1PlaygroundSessionsSessionIdEndPost()
    {
        $config = new Configuration();
        $config->setHost('https://api.zarnite.com');

        $api = new PlaygroundApi(null, $config);
        $request = $api->endSessionV1PlaygroundSessionsSessionIdEndPostRequest('session_1', ['status' => 'ended']);

        self::assertSame('POST', $request->getMethod());
        self::assertStringContainsString('/v1/playground/sessions/session_1/end', (string) $request->getUri());
    }

    /**
     * Test case for markActivityV1PlaygroundSessionsSessionIdActivityPost
     *
     * Mark Activity.
     *
     */
    public function testMarkActivityV1PlaygroundSessionsSessionIdActivityPost()
    {
        $api = new PlaygroundApi();
        $request = $api->markActivityV1PlaygroundSessionsSessionIdActivityPostRequest('session_1');

        self::assertSame('POST', $request->getMethod());
        self::assertStringContainsString('/v1/playground/sessions/session_1/activity', (string) $request->getUri());
    }

    /**
     * Test case for recentTranscriptsV1PlaygroundTranscriptsRecentGet
     *
     * Recent Transcripts.
     *
     */
    public function testRecentTranscriptsV1PlaygroundTranscriptsRecentGet()
    {
        $api = new PlaygroundApi();
        $request = $api->recentTranscriptsV1PlaygroundTranscriptsRecentGetRequest('org_1', 'agent_1', 'user_1', 10);
        $uri = (string) $request->getUri();

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/playground/transcripts/recent', $uri);
        self::assertStringContainsString('org_id=org_1', $uri);
        self::assertStringContainsString('agent_id=agent_1', $uri);
        self::assertStringContainsString('user_id=user_1', $uri);
        self::assertStringContainsString('limit=10', $uri);
    }

    /**
     * Test case for sessionDiagnosticsV1PlaygroundSessionsSessionIdDiagnosticsGet
     *
     * Session Diagnostics.
     *
     */
    public function testSessionDiagnosticsV1PlaygroundSessionsSessionIdDiagnosticsGet()
    {
        $api = new PlaygroundApi();
        $request = $api->sessionDiagnosticsV1PlaygroundSessionsSessionIdDiagnosticsGetRequest('session_1');

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/playground/sessions/session_1/diagnostics', (string) $request->getUri());
    }

    /**
     * Test case for sessionMetricsV1PlaygroundSessionsSessionIdMetricsGet
     *
     * Session Metrics.
     *
     */
    public function testSessionMetricsV1PlaygroundSessionsSessionIdMetricsGet()
    {
        $api = new PlaygroundApi();
        $request = $api->sessionMetricsV1PlaygroundSessionsSessionIdMetricsGetRequest('session_1');

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/playground/sessions/session_1/metrics', (string) $request->getUri());
    }

    /**
     * Test case for sessionTranscriptV1PlaygroundSessionsSessionIdTranscriptGet
     *
     * Session Transcript.
     *
     */
    public function testSessionTranscriptV1PlaygroundSessionsSessionIdTranscriptGet()
    {
        $api = new PlaygroundApi();
        $request = $api->sessionTranscriptV1PlaygroundSessionsSessionIdTranscriptGetRequest('session_1');

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/playground/sessions/session_1/transcript', (string) $request->getUri());
    }

    /**
     * Test case for supportedVoicesV1PlaygroundVoicesGet
     *
     * Supported Voices.
     *
     */
    public function testSupportedVoicesV1PlaygroundVoicesGet()
    {
        $api = new PlaygroundApi();
        $request = $api->supportedVoicesV1PlaygroundVoicesGetRequest('org_1', 'user_1');
        $uri = (string) $request->getUri();

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/playground/voices', $uri);
        self::assertStringContainsString('org_id=org_1', $uri);
        self::assertStringContainsString('user_id=user_1', $uri);
    }

    /**
     * Test case for voiceLookupV1PlaygroundVoicesLookupGet
     *
     * Voice Lookup.
     *
     */
    public function testVoiceLookupV1PlaygroundVoicesLookupGet()
    {
        $api = new PlaygroundApi();
        $request = $api->voiceLookupV1PlaygroundVoicesLookupGetRequest('org_1', 'user_1');
        $uri = (string) $request->getUri();

        self::assertSame('GET', $request->getMethod());
        self::assertStringContainsString('/v1/playground/voices/lookup', $uri);
        self::assertStringContainsString('org_id=org_1', $uri);
        self::assertStringContainsString('user_id=user_1', $uri);
    }
}
