<?php
/**
 * RoutingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zarnite Core API
 *
 * Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Zarnite\Test\Api;

use \Zarnite\Configuration;
use \Zarnite\ApiException;
use \Zarnite\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RoutingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Zarnite
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RoutingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getOrgConfigV1RoutingOrgConfigGet
     *
     * Get Org Config.
     *
     */
    public function testGetOrgConfigV1RoutingOrgConfigGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserCategoryV1RoutingUserCategoryGet
     *
     * Get User Category.
     *
     */
    public function testGetUserCategoryV1RoutingUserCategoryGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrgConfigV1RoutingOrgConfigPut
     *
     * Update Org Config.
     *
     */
    public function testUpdateOrgConfigV1RoutingOrgConfigPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUserCategoryV1RoutingUserCategoryPut
     *
     * Update User Category.
     *
     */
    public function testUpdateUserCategoryV1RoutingUserCategoryPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
